// <auto-generated />
using System;
using Clinico.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinico.Infraestructura.Migrations
{
    [DbContext(typeof(ClinicalDbContext))]
    [Migration("20260604153520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinico.Dominio.Entidades.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.AuditoriaIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlertaDetectada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueForzado")
                        .HasColumnType("bit");

                    b.Property<string>("JustificacionClinica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MensajeIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TratamientoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TratamientoId");

                    b.ToTable("AuditoriasIA");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.CatalogoCie10", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Codigo");

                    b.ToTable("CatalogosCie10", (string)null);
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Diagnostico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoCie10")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HistoriaClinicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCie10");

                    b.HasIndex("HistoriaClinicaId");

                    b.HasIndex("MedicoId");

                    b.ToTable("Diagnosticos", (string)null);
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Enfermera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Enfermeras");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.EvolucionClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HistoriaClinicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaClinicaId");

                    b.HasIndex("MedicoId");

                    b.ToTable("EvolucionesClinicas");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.FrecuenciaAdministracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadHoras")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FrecuenciasAdministracion");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.HistoriaClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alergias")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Antecedentes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ObservacionesGenerales")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("HistoriasClinicas", (string)null);
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Medicamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contraindicaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrogaGenerica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EfectosAdversos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Presentacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("RequiereControl")
                        .HasColumnType("bit");

                    b.Property<string>("ViaAdministracion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Medicamentos", (string)null);
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Medicos", (string)null);
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Tratamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiagnosticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Dosis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FrecuenciaAdministracionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticoId");

                    b.HasIndex("FrecuenciaAdministracionId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Tratamientos", (string)null);
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.TratamientoDosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnfermeraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDelSistema")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSuministro")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoOmision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TratamientoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnfermeraId");

                    b.HasIndex("TratamientoId");

                    b.ToTable("TratamientosDosis", (string)null);
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.UnidadMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.AuditoriaIA", b =>
                {
                    b.HasOne("Clinico.Dominio.Entidades.Tratamiento", "Tratamiento")
                        .WithMany("AuditoriasIA")
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Diagnostico", b =>
                {
                    b.HasOne("Clinico.Dominio.Entidades.CatalogoCie10", "CatalogoCie10")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("CodigoCie10")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.HistoriaClinica", "HistoriaClinica")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.Medico", "Medico")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogoCie10");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.EvolucionClinica", b =>
                {
                    b.HasOne("Clinico.Dominio.Entidades.HistoriaClinica", "HistoriaClinica")
                        .WithMany("EvolucionesClinicas")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.Medico", "Medico")
                        .WithMany("EvolucionesClinicas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Tratamiento", b =>
                {
                    b.HasOne("Clinico.Dominio.Entidades.Diagnostico", "Diagnostico")
                        .WithMany("Tratamientos")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.FrecuenciaAdministracion", "FrecuenciaAdministracion")
                        .WithMany("Tratamientos")
                        .HasForeignKey("FrecuenciaAdministracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.Medicamento", "Medicamento")
                        .WithMany("Tratamientos")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.UnidadMedida", "UnidadMedida")
                        .WithMany("Tratamientos")
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnostico");

                    b.Navigation("FrecuenciaAdministracion");

                    b.Navigation("Medicamento");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.TratamientoDosis", b =>
                {
                    b.HasOne("Clinico.Dominio.Entidades.Enfermera", "Enfermera")
                        .WithMany("TratamientosDosis")
                        .HasForeignKey("EnfermeraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.Tratamiento", "Tratamiento")
                        .WithMany("DosisProgramadas")
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfermera");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.CatalogoCie10", b =>
                {
                    b.Navigation("Diagnosticos");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Diagnostico", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Enfermera", b =>
                {
                    b.Navigation("TratamientosDosis");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.FrecuenciaAdministracion", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.HistoriaClinica", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("EvolucionesClinicas");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Medicamento", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Medico", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("EvolucionesClinicas");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Tratamiento", b =>
                {
                    b.Navigation("AuditoriasIA");

                    b.Navigation("DosisProgramadas");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.UnidadMedida", b =>
                {
                    b.Navigation("Tratamientos");
                });
#pragma warning restore 612, 618
        }
    }
}
