// <auto-generated />
using System;
using Clinico.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinico.Infraestructura.Migrations
{
    [DbContext(typeof(ContextoBaseDeDatos))]
    [Migration("20260627043400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinico.Dominio.Entidades.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Auditorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Accion = "Crear",
                            Descripcion = "Se registró un nuevo diagnóstico de Sinusitis aguda.",
                            Entidad = "Diagnostico",
                            EntidadId = new Guid("11111111-dddd-dddd-dddd-111111111111"),
                            FechaHora = new DateTime(2026, 6, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            PayloadJson = "{\"CodigoCie10\": \"J01.9\"}",
                            Rol = "Medico",
                            UsuarioId = "22222222-2222-2222-2222-222222222222"
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.AuditoriaIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlertaDetectada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueForzado")
                        .HasColumnType("bit");

                    b.Property<string>("JustificacionClinica")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MensajeIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TratamientoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TratamientoId");

                    b.ToTable("AuditoriasIA", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AlertaDetectada = true,
                            FechaHora = new DateTime(2026, 6, 16, 10, 30, 0, 0, DateTimeKind.Utc),
                            FueForzado = true,
                            JustificacionClinica = "El paciente presenta dolor agudo inmanejable. Se administrará dosis baja y se monitoreará la presión arterial cada 8 horas.",
                            MensajeIA = "⚠️ Precaución: El uso de AINEs (Ibuprofeno) puede aumentar la presión arterial en pacientes hipertensos.",
                            NivelRiesgo = "Medio",
                            TratamientoId = new Guid("66666666-7777-7777-7777-666666666666")
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.CatalogoCie10", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Codigo");

                    b.ToTable("CatalogosCie10", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = "J01.9",
                            Categoria = "Enfermedades del sistema respiratorio",
                            Descripcion = "Sinusitis aguda, no especificada"
                        },
                        new
                        {
                            Codigo = "I10",
                            Categoria = "Enfermedades del sistema circulatorio",
                            Descripcion = "Hipertensión esencial (primaria)"
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Diagnostico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoCie10")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HistoriaClinicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCie10");

                    b.HasIndex("HistoriaClinicaId");

                    b.HasIndex("MedicoId");

                    b.ToTable("Diagnosticos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-dddd-dddd-dddd-111111111111"),
                            CodigoCie10 = "J01.9",
                            FechaHora = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HistoriaClinicaId = new Guid("aaaaaaaa-1111-1111-1111-aaaaaaaaaaaa"),
                            MedicoId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Observaciones = "Paciente presenta cuadro de congestión y dolor facial agudo."
                        },
                        new
                        {
                            Id = new Guid("22222222-dddd-dddd-dddd-222222222222"),
                            CodigoCie10 = "I10",
                            FechaHora = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HistoriaClinicaId = new Guid("bbbbbbbb-2222-2222-2222-bbbbbbbbbbbb"),
                            MedicoId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Observaciones = "Presión arterial elevada en múltiples tomas. Requiere inicio de tratamiento."
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Enfermera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Legajo")
                        .IsUnique();

                    b.ToTable("Enfermeras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Legajo = "ENF-1001",
                            Nombre = "Enf. Rodrigo Godoy",
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Legajo = "ENF-1002",
                            Nombre = "Enf. Matías Silva",
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.EvolucionClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HistoriaClinicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaClinicaId");

                    b.ToTable("EvolucionesClinicas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            FechaHora = new DateTime(2026, 6, 16, 18, 0, 0, 0, DateTimeKind.Utc),
                            HistoriaClinicaId = new Guid("aaaaaaaa-1111-1111-1111-aaaaaaaaaaaa"),
                            MedicoId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Observacion = "Paciente refiere alivio leve del dolor facial tras la primera dosis de Amoxicilina. Afebril. Continúa en observación."
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.FrecuenciaAdministracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadHoras")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("FrecuenciasAdministracion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-6666-6666-6666-333333333333"),
                            CantidadHoras = 8,
                            Descripcion = "Cada 8 horas"
                        },
                        new
                        {
                            Id = new Guid("44444444-6666-6666-6666-444444444444"),
                            CantidadHoras = 12,
                            Descripcion = "Cada 12 horas"
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.HistoriaClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alergias")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Antecedentes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ObservacionesGenerales")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("HistoriasClinicas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-aaaaaaaaaaaa"),
                            Alergias = "Penicilina",
                            Antecedentes = "Hipertensión controlada",
                            GrupoSanguineo = "A+",
                            ObservacionesGenerales = "Paciente ingresa por guardia clínica.",
                            PacienteId = new Guid("11111111-aaaa-aaaa-aaaa-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-bbbbbbbbbbbb"),
                            Alergias = "Ninguna conocida",
                            Antecedentes = "Asma en la infancia",
                            GrupoSanguineo = "O-",
                            ObservacionesGenerales = "Paciente derivado de consultorios externos.",
                            PacienteId = new Guid("22222222-bbbb-bbbb-bbbb-222222222222")
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Medicamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contraindicaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrogaGenerica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EfectosAdversos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Presentacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("RequiereControl")
                        .HasColumnType("bit");

                    b.Property<int>("ViaAdministracion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Medicamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-cccccccccccc"),
                            DrogaGenerica = "Amoxicilina",
                            NombreComercial = "Amoxidal 500",
                            Presentacion = "Comprimidos",
                            RequiereControl = false,
                            ViaAdministracion = 1
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-dddddddddddd"),
                            DrogaGenerica = "Ibuprofeno",
                            NombreComercial = "Ibuprofeno 600",
                            Presentacion = "Comprimidos recubiertos",
                            RequiereControl = false,
                            ViaAdministracion = 1
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Medicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Especialidad = "Clínica Médica",
                            Matricula = "MN-123456",
                            Nombre = "Dr. Alejandro Salas"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Especialidad = "Terapia Intensiva",
                            Matricula = "MN-654321",
                            Nombre = "Dr. Yonatan Rojas"
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Tratamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiagnosticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Dosis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FrecuenciaAdministracionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticoId");

                    b.HasIndex("FrecuenciaAdministracionId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Tratamientos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-7777-7777-7777-555555555555"),
                            DiagnosticoId = new Guid("11111111-dddd-dddd-dddd-111111111111"),
                            Dosis = 500m,
                            Estado = 1,
                            FechaFin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FrecuenciaAdministracionId = new Guid("33333333-6666-6666-6666-333333333333"),
                            MedicamentoId = new Guid("cccccccc-3333-3333-3333-cccccccccccc"),
                            UnidadMedidaId = new Guid("11111111-5555-5555-5555-111111111111")
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-7777-7777-666666666666"),
                            DiagnosticoId = new Guid("22222222-dddd-dddd-dddd-222222222222"),
                            Dosis = 600m,
                            Estado = 1,
                            FechaFin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FrecuenciaAdministracionId = new Guid("44444444-6666-6666-6666-444444444444"),
                            MedicamentoId = new Guid("dddddddd-4444-4444-4444-dddddddddddd"),
                            UnidadMedidaId = new Guid("11111111-5555-5555-5555-111111111111")
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.TratamientoDosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EnfermeraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDelSistema")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSuministro")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoOmision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TratamientoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnfermeraId");

                    b.HasIndex("TratamientoId");

                    b.ToTable("TratamientosDosis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-1111-8888-8888-777777777777"),
                            Estado = 1,
                            FechaProgramada = new DateTime(2026, 6, 23, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TratamientoId = new Guid("55555555-7777-7777-7777-555555555555")
                        },
                        new
                        {
                            Id = new Guid("77777777-2222-8888-8888-777777777777"),
                            Estado = 1,
                            FechaProgramada = new DateTime(2026, 6, 23, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TratamientoId = new Guid("55555555-7777-7777-7777-555555555555")
                        },
                        new
                        {
                            Id = new Guid("77777777-3333-8888-8888-777777777777"),
                            EnfermeraId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Estado = 2,
                            FechaDelSistema = new DateTime(2026, 6, 24, 8, 15, 30, 0, DateTimeKind.Unspecified),
                            FechaProgramada = new DateTime(2026, 6, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSuministro = new DateTime(2026, 6, 24, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            TratamientoId = new Guid("55555555-7777-7777-7777-555555555555")
                        },
                        new
                        {
                            Id = new Guid("77777777-4444-8888-8888-777777777777"),
                            Estado = 1,
                            FechaProgramada = new DateTime(2026, 6, 24, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TratamientoId = new Guid("55555555-7777-7777-7777-555555555555")
                        },
                        new
                        {
                            Id = new Guid("77777777-5555-8888-8888-777777777777"),
                            Estado = 1,
                            FechaProgramada = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TratamientoId = new Guid("55555555-7777-7777-7777-555555555555")
                        },
                        new
                        {
                            Id = new Guid("77777777-6666-8888-8888-777777777777"),
                            Estado = 1,
                            FechaProgramada = new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TratamientoId = new Guid("55555555-7777-7777-7777-555555555555")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-8888-8888-777777777777"),
                            Estado = 1,
                            FechaProgramada = new DateTime(2026, 6, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TratamientoId = new Guid("55555555-7777-7777-7777-555555555555")
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-8888-8888-888888888888"),
                            Estado = 1,
                            FechaProgramada = new DateTime(2026, 6, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TratamientoId = new Guid("66666666-7777-7777-7777-666666666666")
                        },
                        new
                        {
                            Id = new Guid("88888888-2222-8888-8888-888888888888"),
                            Estado = 1,
                            FechaProgramada = new DateTime(2026, 6, 24, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TratamientoId = new Guid("66666666-7777-7777-7777-666666666666")
                        },
                        new
                        {
                            Id = new Guid("88888888-3333-8888-8888-888888888888"),
                            Estado = 1,
                            FechaProgramada = new DateTime(2026, 6, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TratamientoId = new Guid("66666666-7777-7777-7777-666666666666")
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.UnidadMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-5555-5555-5555-111111111111"),
                            Abreviatura = "mg",
                            Nombre = "Miligramos"
                        },
                        new
                        {
                            Id = new Guid("22222222-5555-5555-5555-222222222222"),
                            Abreviatura = "ml",
                            Nombre = "Mililitros"
                        });
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.AuditoriaIA", b =>
                {
                    b.HasOne("Clinico.Dominio.Entidades.Tratamiento", "Tratamiento")
                        .WithMany("AuditoriasIA")
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Diagnostico", b =>
                {
                    b.HasOne("Clinico.Dominio.Entidades.CatalogoCie10", "CatalogoCie10")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("CodigoCie10")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.HistoriaClinica", "HistoriaClinica")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.Medico", "Medico")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogoCie10");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.EvolucionClinica", b =>
                {
                    b.HasOne("Clinico.Dominio.Entidades.HistoriaClinica", "HistoriaClinica")
                        .WithMany("EvolucionesClinicas")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoriaClinica");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Tratamiento", b =>
                {
                    b.HasOne("Clinico.Dominio.Entidades.Diagnostico", "Diagnostico")
                        .WithMany("Tratamientos")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.FrecuenciaAdministracion", "FrecuenciaAdministracion")
                        .WithMany("Tratamientos")
                        .HasForeignKey("FrecuenciaAdministracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.Medicamento", "Medicamento")
                        .WithMany("Tratamientos")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinico.Dominio.Entidades.UnidadMedida", "UnidadMedida")
                        .WithMany("Tratamientos")
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnostico");

                    b.Navigation("FrecuenciaAdministracion");

                    b.Navigation("Medicamento");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.TratamientoDosis", b =>
                {
                    b.HasOne("Clinico.Dominio.Entidades.Enfermera", "Enfermera")
                        .WithMany("TratamientosDosis")
                        .HasForeignKey("EnfermeraId");

                    b.HasOne("Clinico.Dominio.Entidades.Tratamiento", "Tratamiento")
                        .WithMany("DosisProgramadas")
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfermera");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.CatalogoCie10", b =>
                {
                    b.Navigation("Diagnosticos");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Diagnostico", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Enfermera", b =>
                {
                    b.Navigation("TratamientosDosis");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.FrecuenciaAdministracion", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.HistoriaClinica", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("EvolucionesClinicas");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Medicamento", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Medico", b =>
                {
                    b.Navigation("Diagnosticos");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.Tratamiento", b =>
                {
                    b.Navigation("AuditoriasIA");

                    b.Navigation("DosisProgramadas");
                });

            modelBuilder.Entity("Clinico.Dominio.Entidades.UnidadMedida", b =>
                {
                    b.Navigation("Tratamientos");
                });
#pragma warning restore 612, 618
        }
    }
}
